"""
Kernel Registry - Definitions for all supported language kernels.

Each kernel definition includes:
  - display_name: Human-readable name
  - file_extension: File extension for temp files
  - mime_type: MIME type for syntax highlighting
  - binary: The executable name
  - compile_cmd: Compilation command (if compiled language), {file} and {output} are replaced
  - run_cmd: Run command, {file} and {output} are replaced
  - exec_mode: "subprocess" (default) or "jupyter"
  - docker_image: Docker image for isolated execution
  - jupyter_kernel: Jupyter kernel name (if available)
  - icon: Emoji or icon identifier
"""

KERNEL_REGISTRY: dict[str, dict] = {
    # ──── Interpreted Languages ────

    "python": {
        "display_name": "Python 3",
        "file_extension": ".py",
        "mime_type": "text/x-python",
        "binary": "python",
        "run_cmd": ["python", "-u", "{file}"],
        "exec_mode": "subprocess",
        "docker_image": "mbmbook-kernel-python",
        "jupyter_kernel": "python3",
        "icon": "🐍",
    },
    "javascript": {
        "display_name": "JavaScript (Node.js)",
        "file_extension": ".js",
        "mime_type": "text/javascript",
        "binary": "node",
        "run_cmd": ["node", "{file}"],
        "exec_mode": "subprocess",
        "docker_image": "mbmbook-kernel-node",
        "jupyter_kernel": "javascript",
        "icon": "🟨",
    },
    "typescript": {
        "display_name": "TypeScript (tsx/Deno)",
        "file_extension": ".ts",
        "mime_type": "text/typescript",
        "binary": "npx",
        "run_cmd": ["npx", "tsx", "{file}"],
        "exec_mode": "subprocess",
        "docker_image": "mbmbook-kernel-node",
        "icon": "🔷",
    },
    "r": {
        "display_name": "R",
        "file_extension": ".R",
        "mime_type": "text/x-r",
        "binary": "Rscript",
        "run_cmd": ["Rscript", "{file}"],
        "exec_mode": "subprocess",
        "docker_image": "mbmbook-kernel-r",
        "jupyter_kernel": "ir",
        "icon": "📊",
    },
    "julia": {
        "display_name": "Julia",
        "file_extension": ".jl",
        "mime_type": "text/x-julia",
        "binary": "julia",
        "run_cmd": ["julia", "{file}"],
        "exec_mode": "subprocess",
        "docker_image": "mbmbook-kernel-julia",
        "jupyter_kernel": "julia-1.10",
        "icon": "🟣",
    },
    "ruby": {
        "display_name": "Ruby",
        "file_extension": ".rb",
        "mime_type": "text/x-ruby",
        "binary": "ruby",
        "run_cmd": ["ruby", "{file}"],
        "exec_mode": "subprocess",
        "docker_image": "mbmbook-kernel-ruby",
        "icon": "💎",
    },
    "php": {
        "display_name": "PHP",
        "file_extension": ".php",
        "mime_type": "text/x-php",
        "binary": "php",
        "run_cmd": ["php", "{file}"],
        "exec_mode": "subprocess",
        "docker_image": "mbmbook-kernel-php",
        "icon": "🐘",
    },
    "perl": {
        "display_name": "Perl",
        "file_extension": ".pl",
        "mime_type": "text/x-perl",
        "binary": "perl",
        "run_cmd": ["perl", "{file}"],
        "exec_mode": "subprocess",
        "docker_image": "mbmbook-kernel-perl",
        "icon": "🐪",
    },
    "lua": {
        "display_name": "Lua",
        "file_extension": ".lua",
        "mime_type": "text/x-lua",
        "binary": "lua",
        "run_cmd": ["lua", "{file}"],
        "exec_mode": "subprocess",
        "docker_image": "mbmbook-kernel-lua",
        "icon": "🌙",
    },
    "bash": {
        "display_name": "Bash / Shell",
        "file_extension": ".sh",
        "mime_type": "text/x-sh",
        "binary": "bash",
        "run_cmd": ["bash", "{file}"],
        "exec_mode": "subprocess",
        "docker_image": "mbmbook-kernel-base",
        "icon": "🐚",
    },
    "powershell": {
        "display_name": "PowerShell",
        "file_extension": ".ps1",
        "mime_type": "text/x-powershell",
        "binary": "pwsh",
        "run_cmd": ["pwsh", "-File", "{file}"],
        "exec_mode": "subprocess",
        "docker_image": "mbmbook-kernel-powershell",
        "icon": "⚡",
    },

    # ──── Compiled Languages ────

    "c": {
        "display_name": "C (GCC)",
        "file_extension": ".c",
        "mime_type": "text/x-csrc",
        "binary": "gcc",
        "compile_cmd": ["gcc", "-o", "{output}", "{file}", "-lm"],
        "run_cmd": ["{output}"],
        "exec_mode": "subprocess",
        "docker_image": "mbmbook-kernel-cpp",
        "icon": "🔵",
    },
    "cpp": {
        "display_name": "C++ (G++)",
        "file_extension": ".cpp",
        "mime_type": "text/x-c++src",
        "binary": "g++",
        "compile_cmd": ["g++", "-std=c++20", "-o", "{output}", "{file}"],
        "run_cmd": ["{output}"],
        "exec_mode": "subprocess",
        "docker_image": "mbmbook-kernel-cpp",
        "icon": "🔵",
    },
    "java": {
        "display_name": "Java",
        "file_extension": ".java",
        "mime_type": "text/x-java",
        "binary": "javac",
        "compile_cmd": ["javac", "{file}"],
        "run_cmd": ["java", "-cp", "{file_dir}", "{class_name}"],
        "exec_mode": "subprocess",
        "docker_image": "mbmbook-kernel-java",
        "icon": "☕",
    },
    "csharp": {
        "display_name": "C# (.NET)",
        "file_extension": ".cs",
        "mime_type": "text/x-csharp",
        "binary": "dotnet-script",
        "run_cmd": ["dotnet-script", "{file}"],
        "exec_mode": "subprocess",
        "docker_image": "mbmbook-kernel-dotnet",
        "jupyter_kernel": ".net-csharp",
        "icon": "🟪",
    },
    "go": {
        "display_name": "Go",
        "file_extension": ".go",
        "mime_type": "text/x-go",
        "binary": "go",
        "run_cmd": ["go", "run", "{file}"],
        "exec_mode": "subprocess",
        "docker_image": "mbmbook-kernel-go",
        "jupyter_kernel": "gophernotes",
        "icon": "🐹",
    },
    "rust": {
        "display_name": "Rust",
        "file_extension": ".rs",
        "mime_type": "text/x-rust",
        "binary": "rustc",
        "compile_cmd": ["rustc", "-o", "{output}", "{file}"],
        "run_cmd": ["{output}"],
        "exec_mode": "subprocess",
        "docker_image": "mbmbook-kernel-rust",
        "jupyter_kernel": "evcxr",
        "icon": "🦀",
    },
    "kotlin": {
        "display_name": "Kotlin",
        "file_extension": ".kts",
        "mime_type": "text/x-kotlin",
        "binary": "kotlinc",
        "run_cmd": ["kotlinc", "-script", "{file}"],
        "exec_mode": "subprocess",
        "docker_image": "mbmbook-kernel-kotlin",
        "jupyter_kernel": "kotlin",
        "icon": "🟠",
    },
    "scala": {
        "display_name": "Scala",
        "file_extension": ".scala",
        "mime_type": "text/x-scala",
        "binary": "scala",
        "run_cmd": ["scala", "{file}"],
        "exec_mode": "subprocess",
        "docker_image": "mbmbook-kernel-scala",
        "jupyter_kernel": "almond",
        "icon": "🔴",
    },
    "swift": {
        "display_name": "Swift",
        "file_extension": ".swift",
        "mime_type": "text/x-swift",
        "binary": "swift",
        "run_cmd": ["swift", "{file}"],
        "exec_mode": "subprocess",
        "docker_image": "mbmbook-kernel-swift",
        "icon": "🍎",
    },
    "haskell": {
        "display_name": "Haskell",
        "file_extension": ".hs",
        "mime_type": "text/x-haskell",
        "binary": "runhaskell",
        "run_cmd": ["runhaskell", "{file}"],
        "exec_mode": "subprocess",
        "docker_image": "mbmbook-kernel-haskell",
        "jupyter_kernel": "haskell",
        "icon": "🟤",
    },

    # ──── Data & Scientific ────

    "sql": {
        "display_name": "SQL",
        "file_extension": ".sql",
        "mime_type": "text/x-sql",
        "binary": "sqlite3",
        "run_cmd": ["sqlite3", ":memory:", ".read {file}"],
        "exec_mode": "subprocess",
        "docker_image": "mbmbook-kernel-sql",
        "icon": "🗃️",
    },
    "octave": {
        "display_name": "Octave (MATLAB-compatible)",
        "file_extension": ".m",
        "mime_type": "text/x-octave",
        "binary": "octave",
        "run_cmd": ["octave", "--no-gui", "{file}"],
        "exec_mode": "subprocess",
        "docker_image": "mbmbook-kernel-octave",
        "jupyter_kernel": "octave",
        "icon": "📐",
    },

    # ──── Systems / Low-level ────

    "assembly": {
        "display_name": "Assembly (NASM x86_64)",
        "file_extension": ".asm",
        "mime_type": "text/x-asm",
        "binary": "nasm",
        "compile_cmd": ["nasm", "-f", "elf64", "-o", "{output}.o", "{file}"],
        "run_cmd": ["ld", "-o", "{output}", "{output}.o"],
        "exec_mode": "subprocess",
        "docker_image": "mbmbook-kernel-asm",
        "icon": "⚙️",
    },
    "zig": {
        "display_name": "Zig",
        "file_extension": ".zig",
        "mime_type": "text/x-zig",
        "binary": "zig",
        "run_cmd": ["zig", "run", "{file}"],
        "exec_mode": "subprocess",
        "docker_image": "mbmbook-kernel-zig",
        "icon": "⚡",
    },

    # ──── Markup / Config (rendered, not executed) ────

    "markdown": {
        "display_name": "Markdown",
        "file_extension": ".md",
        "mime_type": "text/markdown",
        "exec_mode": "render",
        "icon": "📝",
    },
    "html": {
        "display_name": "HTML",
        "file_extension": ".html",
        "mime_type": "text/html",
        "exec_mode": "render",
        "docker_image": "mbmbook-kernel-base",
        "icon": "🌐",
    },
}
